#!/usr/bin/env python3.10
import os

def check_makefile(test, total_test):
    if os.path.isfile('Makefile'):
        test += 1
    else:
        print("Makefile does not exist.")
    return test, total_test + 1

if __name__ == "__main__":
    test = 0
    total_test = 0

    test, total_test = check_makefile(test, total_test)

    print(f"Test : {test}/{total_test}")
